name = "blackhole-storm-lb"
main = "worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "blackhole-storm"
database_id = "PASTE-THE-ID-FROM-wrangler-d1-create"
